### ISSUE TITLE
example1 Segmentation fault

### ISSUE THREAD

**Issue by LucaDanelutti** [AutomataLab/Pison#2]
I was trying to replicate a bunch of experiments from a related project and I came across segmentation fault errors with the Pison engine. So, I tried running the examples you provide inside this repository and example1 gives me a segmentation fault. 

A couple of details:
- clean clone of the repository
- gcc version 9.4.0
- g++ throws a couple of warnings related to string constant conversions to char*, but I don't think they could be the problem 
- running on a vm with an Intel(R) Xeon(R) Gold 6354 CPU @ 3.00GHz 4x cores + hyperthreading, 55GB of RAM. If I'm not wrong the CPU supports the simd instructions that Pison requires
- compiling and running the example with thread_num=1 works fine, any number !=1 makes the program crash

What could be the cause of the problem?

**Comment by githubdudu** [comment]
Hi, I'm trying to locate the problem.
1. Can you provide more information about your environment ? Is it Unix, Mac or Window? 
2. Would this error occur with thread_num != 1 in other three examples?

Appreciate~
